#!/bin/bash
#Backup and create file and add first line
var='date +%s'
sudo mv /etc/ppp/ip-up /etc/ppp/ip-up_$var.bak
sudo touch /etc/ppp/ip-up
sudo echo "#!/bin/sh" > /etc/ppp/ip-up

# Available Variables
#       $1      the interface name used by pppd (e.g. ppp3)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd

# This script will conditionally add routes based on the connections IP range
# It will backup and replace any existing file at /etc/ppp/ip-up
## In this example, the VPN provides an IP address in the 172.16.20.0/24 subnet
## In this example, the client computer needs to route to 10.100.10.0/24, 10.200.20.0/24, and 192.168.0.0/20
## This script will only apply if it's given address matches the IF statement

### Example 1
sudo echo "if [[ "\$"4 == \"172.16.20.\"* ]] ; then" >> /etc/ppp/ip-up
sudo echo "/sbin/route add -net 10.100.10.0/24 -interface "\$"1" >> /etc/ppp/ip-up
sudo echo "/sbin/route add -net 10.200.20.0/24 -interface "\$"1" >> /etc/ppp/ip-up
sudo echo "/sbin/route add -net 192.168.0.0/20 -interface "\$"1" >> /etc/ppp/ip-up
sudo echo "fi" >> /etc/ppp/ip-up

sudo chown root /etc/ppp/ip-up
sudo chmod 755 /etc/ppp/ip-up
